version: '3'

services:
  nginx:
    image: app_nginx:latest
    depends_on:
      - api
    networks:
      - default
    ports:
      - 80:80
    logging: &logging
      driver: json-file

  api:
    image: resolver:latest
    networks:
      - default
    ports:
      - 5632:5632
    logging:
      <<: *logging
